spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: dept-emp-service
          uri: lb://dept-emp-service
          predicates:
            - Path=/organize/**

server:
 port:
    8084